const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'js', 'supabaseConfig.js');

try {
    if (!fs.existsSync(envPath)) {
        console.error('Error: .env file not found.');
        process.exit(1);
    }

    const envFile = fs.readFileSync(envPath, 'utf-8');
    const lines = envFile.split('\n');
    let url = '';
    let key = '';

    lines.forEach(line => {
        const trimmed = line.trim();
        // Ignore comments and empty lines
        if (trimmed && !trimmed.startsWith('#')) {
            if (trimmed.startsWith('SUPABASE_URL=')) {
                url = trimmed.substring('SUPABASE_URL='.length).trim();
            }
            if (trimmed.startsWith('SUPABASE_ANON_KEY=')) {
                key = trimmed.substring('SUPABASE_ANON_KEY='.length).trim();
            }
        }
    });

    const jsContent = `// AUTO-GENERATED FROM .env
// Do not edit this file directly. Edit .env and run node generate-config.js
window.SUPABASE_URL = '${url}';
window.SUPABASE_ANON_KEY = '${key}';
`;

    fs.writeFileSync(configPath, jsContent);
    console.log('✅ Successfully generated js/supabaseConfig.js from .env');
} catch (error) {
    console.error('Error reading .env file:', error.message);
    process.exit(1);
}
